# Generated by Django 2.0.1 on 2018-03-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RelatingLatin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('annotations', models.ManyToManyField(related_query_name='annotations', to='literature.Annotation')),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='slug',
            field=models.SlugField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='translation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatinglatin',
            name='relating_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literature.Text'),
        ),
    ]
