# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
