# Generated by Django 2.0.1 on 2018-01-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=128)),
                ('latin', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
            ],
        ),
    ]
